// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Web_projekat.Migrations
{
    [DbContext(typeof(ZeleznicaContext))]
    [Migration("20220322225157_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Ruta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ruta");
                });

            modelBuilder.Entity("Models.RutaStanica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RutaID")
                        .HasColumnType("int");

                    b.Property<int?>("StanicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RutaID");

                    b.HasIndex("StanicaID");

                    b.ToTable("RutaStanica");
                });

            modelBuilder.Entity("Models.Stanica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GodinaIzgradnje")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Stanica");
                });

            modelBuilder.Entity("Models.Voz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj_Putnika")
                        .HasColumnType("int");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RutaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RutaID");

                    b.ToTable("Voz");
                });

            modelBuilder.Entity("Models.VozUStanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PristigliPutnici")
                        .HasColumnType("int");

                    b.Property<int?>("StanicaID")
                        .HasColumnType("int");

                    b.Property<int?>("VozID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vreme_Dolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vreme_Odlaska")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("StanicaID");

                    b.HasIndex("VozID");

                    b.ToTable("VozUStanici");
                });

            modelBuilder.Entity("Models.RutaStanica", b =>
                {
                    b.HasOne("Models.Ruta", "Ruta")
                        .WithMany("ListaRutaStanica")
                        .HasForeignKey("RutaID");

                    b.HasOne("Models.Stanica", "Stanica")
                        .WithMany("ListaRutaStanica")
                        .HasForeignKey("StanicaID");

                    b.Navigation("Ruta");

                    b.Navigation("Stanica");
                });

            modelBuilder.Entity("Models.Voz", b =>
                {
                    b.HasOne("Models.Ruta", "Ruta")
                        .WithMany("ListaVozova")
                        .HasForeignKey("RutaID");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("Models.VozUStanici", b =>
                {
                    b.HasOne("Models.Stanica", "Stanica")
                        .WithMany()
                        .HasForeignKey("StanicaID");

                    b.HasOne("Models.Voz", "Voz")
                        .WithMany()
                        .HasForeignKey("VozID");

                    b.Navigation("Stanica");

                    b.Navigation("Voz");
                });

            modelBuilder.Entity("Models.Ruta", b =>
                {
                    b.Navigation("ListaRutaStanica");

                    b.Navigation("ListaVozova");
                });

            modelBuilder.Entity("Models.Stanica", b =>
                {
                    b.Navigation("ListaRutaStanica");
                });
#pragma warning restore 612, 618
        }
    }
}
